### ISSUE TITLE
Unable to use columns as return values in case_when

### ISSUE THREAD

**Issue by bakera81** [machow/siuba#101]
When the returns are individual values, this works as expected:
```
df = pd.DataFrame([{'a': 1, 'b': 2}, {'a':3, 'b': 3}])

(
df 
>> mutate(new_col = case_when({_.a == _.b: True, True: False}))
)
```

But if you want to return the columns themselves, it throws `ValueError: invalid __array_struct__`:
```
df = pd.DataFrame([{'a': 1, 'b': 2}, {'a':3, 'b': 3}])

(
df 
>> mutate(new_col = case_when({_.a == _.b: _.a, True: _.b}))
)
```

**Comment by machow** [comment]
should work now in v0.0.10!

https://github.com/machow/siuba/blob/master/siuba/tests/test_verb_case_when.py
