### ISSUE TITLE
how to count distinct number in each group 

### ISSUE THREAD

**Issue by TonyFly3000** [machow/siuba#153]
counting row count for each cyl group:
```{python}
data001=mtcars>> group_by(_.cyl)>> summarize(car_num = count())
print(data001)
```

How to get unique am count for each cyl group in siuba ?
in R will be
mtcars%>% group_by(cyl)%>%summarize(am_count = n_distinct(am))

Thank you

**Comment by TonyFly3000** [comment]
I think I just found the solution 

```{python}
data001=mtcars>> group_by(_.cyl)>> summarize(am_num = _.am.nunique())
print(data001)
```

**Comment by machow** [comment]
Hey, that's exactly right--if you hit any more questions, feel free to keep posting here, and I can be sure to add some answers to the docs (maybe as a common dplyr -> pandas reference?)

**Comment by TonyFly3000** [comment]
1.left_join  is not working with pipe line 

```{python}
data001=table001>>left_join(table002,on = {"cyl": "cyl"}) 
```
TypeError: join() missing 1 required positional argument: 'right'

Detailed traceback: 
  File "<string>", line 1, in <module>
  File "C:\Users\User\ANACON~2\lib\site-packages\siuba\dply\verbs.py", line 174, in wrapper
    return dispatch_func(*strip_args, **strip_kwargs)
  File "C:\Users\User\ANACON~2\lib\functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)

I need to change to 

```{python}
table001=mtcars.head(2)>>mutate(mpg_a=_.mpg)>>select(_.cyl,_.mpg_a)
table002=mtcars.head(3)>>mutate(disp_b=_.disp)>>select(_.cyl,_.disp_b)
data001=left_join(table001,table002,on = {"cyl": "cyl"})
print(data001)
```

**Comment by machow** [comment]
## left_join in pipe

 For the left_join, you need to add an _ as the first argument when used in a pipe (I want to simplify in the future so the code you posted works!)

```
from siuba import _, inner_join, left_join, full_join

df1 = pd.DataFrame({'id': [1,2], 'x': ['a', 'b']})
df2 = pd.DataFrame({'id': [2,2,3], 'y': ['l', 'm', 'n']})

# without pipe
inner_join(df1, df2, on = "id")

# with pipe
df1 >> inner_join(_, df2, on = "id")
```


## using column whose name conflicts with a pandas method

This is a classic pandas problem, and you can always use indexing to get the column.

E.g. changing `_.pop` to `_["pop"]`

```python
summarize(pop_m=_.pop.sum()/1000000)
```

to 

```python
summarize(pop_m= _["pop"].sum()/1000000)
```

**Comment by machow** [comment]
I updated the docs with a section for questions Dplyr users might have, and clarified how to pipe joins. Thanks again for your questions--feel free to open an issue again if you hit more!

https://siuba.readthedocs.io/en/latest/dplyr_faq.html

https://siuba.readthedocs.io/en/latest/api_table_two/joins.html
