### ISSUE TITLE
investigate tab autocompletion

### ISSUE THREAD

**Issue by machow** [machow/siuba#155]
In pandas, there is some really interesting code in DataFrames that allows autocompletion for cases like...

```
from siuba.data import mtcars

mtcars["mp<tab>
```

It seems unlikely support for things like 

```
mutate(mtcars, _.<tab>)
```

Will be that easy, but I'm curious to see if it is even feasible (without doing some insane / dangerous reaching in to stack frames).

See

* [pandas implementation](https://github.com/takluyver/pandas/blob/master/pandas/core/frame.py#L4239-L4256)
* [ipython completer module](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.completer.html)

**Comment by machow** [comment]
One possible solution would be having `_.<tab>` or _[<tab>]` autocomplete based on the last object IPython holds reference to. E.g. autocomplete for In[-1].

**Comment by tmastny** [comment]
Sharing my notes on this: `IPython.generics.complete_object` from your pandas example is no longer called in the latest version of IPython, which executes [`IPython.core.completer.IPComplete._complete`](https://github.com/ipython/ipython/blob/fdd327591569ec5fc1d5c6d79f41df48bf5162b0/IPython/core/completer.py#L1934). 

`IPython.generics.complete_object` is only called in [`IPython.core.completer.Complete.complete`](https://github.com/ipython/ipython/blob/fdd327591569ec5fc1d5c6d79f41df48bf5162b0/IPython/core/completer.py#L732) via `IPython.core.completer.Complete.attr_matches`.

**Comment by machow** [comment]
Released--thanks!
