### ISSUE TITLE
Ask what level of doc overlap dplyr crew is okay with

### ISSUE THREAD

**Issue by machow** [machow/siuba#174]
@hadley, @romainfrancois - I've been working on this port of dplyr to python. It currently has the following

* piping mechanism, symbolic expressions
* ports of many dplyr, tidyr, and some forcat functions
* support for SQL, and pandas (grouped) DataFrames

**However, it seems like the first thing I often need to explain to people is exactly what is listed first in the dplyr docs: the five big dplyr verbs.**

I've been sitting on a re-write of siuba's README for a while, since its intro is extremely similar to dplyr's, so figured I would check in on it.

Are you okay with siuba's README intro having this level of similarity? I'm happy to modify to give better attribution, or change the intro entirely.

### Comparison of intros (currently on a branch)

https://github.com/machow/siuba/tree/doc-better-readme

![image](https://user-images.githubusercontent.com/2574498/72470947-b4c78300-37af-11ea-833d-04c4cb852dcd.png)

![image](https://user-images.githubusercontent.com/2574498/72470965-bdb85480-37af-11ea-9687-c63f8aae2d40.png)

**Comment by hadley** [comment]
Yeah, that's fine with me. I think the level of attribution is appropriate.

**Comment by machow** [comment]
Thanks for your quick input--drawing on the careful work put in explaining `dplyr` to newcomers is a huge boon for introducing similar ideas to python folks :).
