### ISSUE TITLE
What summarization fucntions are there?

### ISSUE THREAD

**Issue by xiaodaigh** [machow/siuba#213]
The doc has example for `mean`. What other options are there?

Can the user define their own functions?

**Comment by machow** [comment]
Hey, any Series method that returns a single value (eg the ones you'd use with agg) should work.

For siuba's SQL backend and experimental fast grouped pandas operations, I keep a list here, http://mchow.com/siuba-doc-method-table/

(moving this list into the docs here: #211)

Fast grouped operations and using your own functions are discussed a bit here: https://siuba.readthedocs.io/en/latest/developer/pandas-group-ops.html

I have custom functions for recreating parts of the R library forcats, in case it's helpful as an example:

https://github.com/machow/siuba/blob/master/siuba/dply/forcats.py

I'm working on rounding out the docs this week, and happy to answer any other questions!

**Comment by machow** [comment]
A really simple example might be the lead function, implemented in `siuba.dply.vector`. This function is designed to behave the same as in dplyr, and just uses pandas Series.shift method under the hood. It's also implemented to run on SeriesGroupBy objects (for fast grouped operations) and SQL

SeriesGroupBy: https://github.com/machow/siuba/blob/master/siuba/dply/vector.py#L332

SQL: https://github.com/machow/siuba/blob/master/siuba/sql/dply/vector.py#L151
