### ISSUE TITLE
Request: Code reference to singledispatch of >> on a dataframe

### ISSUE THREAD

**Issue by RAbraham** [machow/siuba#298]
Hi,
Can you point me to the code where you define a singledispatch on `>>` on a dataframe. i.e.
```
from siuba import group_by, summarize, _
from siuba.data import mtcars

(mtcars
  >> group_by(_.cyl)
  >> summarize(avg_hp = _.hp.mean())
  )
```
How do you do >> on `mtcars` which is a dataframe?

**Comment by machow** [comment]
Hey @RAbraham--it works using the mechanics for right-hand-side methods like `__radd__`.

```python
from siuba import group_by, summarize, _
from siuba.data import mtcars

# a siuba.dply.Pipeable object
f = summarize(avg_hp = _.hp.mean())

# mtcars.__rshift__ doesn't exist, but f.__rrshift__ does,
# so f.__rrshift__(mtcars) gets called
mtcars >> f
```

Here's a [short explanation on Pipeable](https://siuba.readthedocs.io/en/latest/guide_programming.html#Pipeable-class) in siuba's docs, and the behavior for right methods like [radd in python's docs](https://docs.python.org/3/reference/datamodel.html#object.__ror__). 

Is there anything you were thinking of trying out / exploring here? I want to do some quick clean-up of siuba's internals this month, so am happy to answer any questions / help with things!

**Comment by RAbraham** [comment]
Thank you very much for your clear and concise explanation :). 
My reason for asking is that I'm building a Datalog inspired library(mercylog) to work on dataframes. The pseudo code is something like:
```
from mercylog import R, _
db = mercylog.DB(mtcars)
# Implement the __call__ method on DB so I can do the following
# The following code should select a column, similar to select(mtcars, _["cyl"]), IIUC
result = db(R.cyl(_))
```
What I was going for was to  remove the wrapping of the dataframe in a DB object and somehow implement the __call__ method on the dataframe. so I could do `mtcars(R.cyl(_))`. I saw your article on single dispatch in Python and I was trying to see if I could use that.

**Comment by RAbraham** [comment]
My question is answered. So I'll close this ticket. Thanks!

**Comment by machow** [comment]
No problem--hope it helps! I'll have to take a closer look datalog / mercylog a bit more at some point!
