### ISSUE TITLE
How to drop NaN or NaTs?

### ISSUE THREAD

**Issue by omrihar** [machow/siuba#303]
I'm sorry if I'm missing something trivial, but I can't figure out what's the best way to drop NaN or NaTs using `filter` (or any other way).

I saw in the documentation examples with `[True, False, 1]` which then drops the `False`, but if I try this with a datetime column, it will not work (throws the error `TypeError: unsupported operand type(s) for &: 'bool' and 'DatetimeArray'`). And using something like `pd.isnull` also fails since it won't work on Symbolic expressions.

So, how can I easily drop `NaN`s or `NaT`s? Again sorry if it's a trivial thing I'm missing... I really love siuba by the way! It's great :)

**Comment by machow** [comment]
Hey @omrihar, does a method like `_.some_col.notna()` or `~_.some_col.isna()` work? It looks like the right hand side of your `&` isn't a boolean.

One other thing to be careful of, is if you have to complex expressions in python like `a > 1 & b > 2`, you'll likely need to write it as `(a > 1) & (b > 2)`.

If you can post your filter code I can look a bit closer!

**Comment by omrihar** [comment]
Hi @machow, thank you for the really quick reply! I'm embarrassed to say I didn't know about `notna()`.
This works wonderfully!

Thank you very much :)
