### ISSUE TITLE
How to add in a new database backend?

### ISSUE THREAD

**Issue by ctSkennerton** [machow/siuba#305]
This is really amazing work! I tried to use a different database backend and got an error saying that there wasn't a corresponding siuba library. When defining a new backend does it need to be in `siuba.sql.dialects` package or can a class be defined outside of the package?

**Comment by machow** [comment]
Hey, thanks for checking it out! Right now it tries to get them from siuba by default, but you can pass in the translator functions manually to LazyTbl.

https://github.com/machow/siuba/blob/master/siuba/sql/verbs.py#L212

In case it's helpful, there's a vignette on how translation is done here: https://siuba.readthedocs.io/en/latest/developer/sql-translators.html

Happy to answer any questions that come up!

**Comment by ctSkennerton** [comment]
great, thank you!
