### ISSUE TITLE
Investigate pandas rank equating very small numbers with 0

### ISSUE THREAD

**Issue by machow** [machow/siuba#307]
Not sure when this behavior changed, but if you use the pandas' rank method on an object type, then small numbers are ranked the same as 0.

```python
import pandas as pd
pd.__version__                  #1.1.0

df = pd.DataFrame({'x': [5.68434e-14, 0]}) 
df.x.astype("O").rank(method = "dense", na_option = "keep")     # both ranked 1.0
```

Need to check if it's fixed by updating patch version, or if I need change the hypothesis tests to not trigger for now.

**Comment by machow** [comment]
Upgrading to 1.1.5 didn't resolve.

**Comment by machow** [comment]
This is not happening on CI, so must be specific to my mac (architecture, or specific python libraries?)

**Comment by pwwang** [comment]
I don't think it is specific to your Mac. I can reproduce this on my PC:

```python
>>> import pandas as pd
>>> pd.__version__         
'1.2.5'
>>> 
>>> df = pd.DataFrame({'x': [5.68434e-14, 0]}) 
>>> df.x.astype("O").rank(method = "dense", na_option = "keep")     # both ranked 1.0
0    1.0
1    1.0
Name: x, dtype: float64
```

Not sure why it's not reproducing on your CI. However, after a little bit digging, I found the problem:

https://github.com/pandas-dev/pandas/blob/9f6a91ae785b28dc87a3cca9db3a663e2c2973fd/pandas/_libs/algos.pyx#L84-L88
```
cdef inline bint are_diff(object left, object right):
    try:
        return fabs(left - right) > FP_ERR
    except TypeError:
        return left != right
```

https://github.com/pandas-dev/pandas/blob/9f6a91ae785b28dc87a3cca9db3a663e2c2973fd/pandas/_libs/algos.pyx#L63:
```
    float64_t FP_ERR = 1e-13
```

Give it a try:
```python
>>> df = pd.DataFrame({'x': [5.68434e-14, 0]}) 
>>> df.x.astype("O").rank(method = "dense", na_option = "keep") 
0    1.0
1    1.0
Name: x, dtype: float64

>>> df = pd.DataFrame({'x': [5.68434e-13, 0]}) 
>>> df.x.astype("O").rank(method = "dense", na_option = "keep") 
0    2.0
1    1.0
Name: x, dtype: float64
```

**Comment by machow** [comment]
Finally looping back to this--I unfortunately can't remember what triggered the errors (I think it might have been tests using hypothesis, which I could see generating cases like this..). Going to close until it resurfaces. Thanks for chasing down the underlying behavior
