### ISSUE TITLE
Running selection of lines fails if there is any comment in between

### ISSUE THREAD

**Issue by GitHunter0** [machow/siuba#312]
First, congratulations for the amazing project, siuba is really promising!

Let me give an example to explain the issue:
```
from siuba import *
from siuba.data import mtcars
```
This works:
```
mtcars \
>> filter(_.gear != 4) \
>> count(_.gear) 
```
While this throws `SyntaxError: invalid syntax`:
```
mtcars \
>> filter(_.gear != 4) \
# ANY COMMENT
>> count(_.gear) 
```
Comments are a really essential part of a code file, so it would be important that it works, don't you agree?

Lastly, one thing that really bothers me in Python's IDEs is that you are obliged to select all the lines to run multiline-statements. In RStudio it understands that it is all part of the same statement and executes them together. Is there any way to accomplish that via `siuba`?

Thank you very much

`Windows 10 PRO, Python 3.8, siuba  0.0.24`

**Comment by machow** [comment]
Hey, thanks for raising--you can use parentheses to break python expressions across lines, and add comments

```python
(mtcars
  >> group_by(_.cyl)       # some comment
  # some comment
  >> summarize(avg_hp = _.hp.mean())
  )
```

What IDE are you using? Agreed it's not as convenient in python :/, though I most run cell by cell in jupyter lab

**Comment by GitHunter0** [comment]
Hey @machow , thank you for the feedback. The problem with parentheses is that they force you to run all the lines inside of them. However, frequently I just wanna run some of the lines of the code block in order to test them incrementally, as I do in R.

I'm using VScode, but I also tried many others like Spyder and Jupyterlab. Usually I have more than one multiline-statement in each cell, so running cell by cell would not achieve I what aim for. 
RStudio multiline-statement capability is a blessing in my opinion, a simple feature that saves a lot of annoying manual labor.

Thank you for sharing your setup, it is always nice to see a good one.

Just one more thing if I may, does `siuba` have a basic support of metaprogramming analogous to R's Non-Standard Evaluation?

**Comment by machow** [comment]
> does siuba have a basic support of metaprogramming analogous to R's Non-Standard Evaluation?

It does! Expressions created using the underscore like `_.x.mean() + 1` generate an [abstract syntax tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree). 

For example, you can see the tree by printing out the code below...

```python
from siuba import _
_.x.mean() + 1
```

```
█─+
├─█─'__call__'
│ └─█─.
│   ├─█─.
│   │ ├─_
│   │ └─'x'
│   └─'mean'
└─1

```

They're discussed a bit in the programming docs

* https://siuba.readthedocs.io/en/latest/guide_programming.html#Lazy-expressions
* https://siuba.readthedocs.io/en/latest/guide_programming.html#Translating-operations

In python a common way to process abstract syntax trees is using a visitor, which is discussed in [this doc](https://siuba.readthedocs.io/en/latest/developer/call_trees.html)!

**Comment by GitHunter0** [comment]
Great man, I will check that out! Thanks @machow
