### ISSUE TITLE
Non-Standard Evaluation (NSE) with quoted variables

### ISSUE THREAD

**Issue by GitHunter0** [machow/siuba#315]
Hey @machow  , first let me say it is been a treat to use `siuba`. I might be biased towards R (I find `dplyr` and `data.table` superb tools), but `pandas` for me is so cumbersome and clumsy that badly compromises my Python experience. Therefore, in my opinion `siuba` is filling a fundamental gap and I'm very excited to see this project flourish. Also, it is fantastic because it creates an infrastructure to add another backends like SQL (and hopefully [datatable](https://github.com/h2oai/datatable) when that project matures).

Would you mind explaining how to deal with quoted variables in `siuba`? I have an example in `dplyr` below and I'd like to know how to replicate that in `siuba`.

```
library(dplyr)

# METHOD 1: Normal version
df <- 
  mtcars %>% 
  slice(3:6) %>%
  select(am, carb, hp) %>% 
  arrange(am, desc(carb)) 

df %>% 
  group_by(am, carb) %>% 
  mutate(hp_avg = mean(hp))


# METHOD 2: NSE / 'tidy evaluation' with quoted variables
groups = c("am","carb")
var = "hp"
new_var = "hp_avg"

df <- 
  mtcars %>% 
  slice(3:6) %>%
  select(c(groups, var)) %>% 
  arrange( !!sym(groups[1]), desc(!!sym(groups[2])) )  

df %>% 
  group_by(across(groups)) %>%
  # or:
  # group_by( !!sym(groups[1]), !!sym(groups[2]) ) %>% 
  mutate( {{new_var}} := mean(!!sym(var)) )


# METHOD 3: New dplyr approach using .data to deal with quoted variables
df <- 
  mtcars %>% 
  slice(3:6) %>%
  select(c(groups, var)) %>% 
  arrange( .data[[groups[1]]], desc(.data[[groups[2]]]) )

df %>% 
  group_by(.data[[groups[1]]] , .data[[groups[2]]] ) %>%
  mutate( {{new_var}} := mean(.data[[var]]) ) 
```

Siuba syntax trial:
```
from siuba import *
from siuba.data import mtcars

groups = ["am","carb"]
var = "hp"
new_var = "hp_avg"

# This part I managed to get it right
df = (
        mtcars.iloc[2:6] # >> slice(2:6)
        >> select( _[[ groups + [var] ]] )
        >> arrange( _[[ groups[0] ]], - _[[ groups[1] ]] )
        # >> select(_.am, _.carb, _.hp) 
        # >> arrange(_.am, -_.carb)
) 

# This part I don't know how to proceed
( 
    df 
    >> group_by( _[[ groups[0] ]], _[[ groups[1] ]])
    >> mutate( new_var = _[[var]].mean() )
    # >> group_by(am, carb) %>% 
    # >> mutate(hp_avg = mean(hp))
) 
```

As an aside, I could not find `slice()` function, is it going to be implemented?
I would like to do things of this kind:
```
mtcars %>% slice(2:6)
# select first and second last row
mtcars %>% slice( c(1, n()-1) ) 
```

Thank you

**Comment by machow** [comment]
Hey--glad it's been helpful, and appreciate you digging into these areas of siuba! One key difference in siuba is that it's expressions aren't full NSE, but are evaluated right away (into an abstract representation of what you want to do). One way I often test out the NSE-like programming by checking the output of an expression like `_[SOME_VARIABLE]` in the console.

For example,

```python
groups = ["am","carb"]
var = "hp"
new_var = "hp_avg"

# testing NSE ----
_[groups]
```

Prints out this:

```
█─[
├─_
└─['am', 'carb']
```

Which is the exact same output as if you did `_[["am", "carb"]]`!

Some of the more NSE pieces haven't been fully fleshed out, but python syntax already provides some early solutions. Here's how I'd write your second piece of code in siuba (there's def room for siuba to improve here)

```python
# This part I don't know how to proceed
( 
    mtcars

    >> group_by(_[groups[0]], _[groups[1]])
    # equivalent to below, need to support _[groups] in the future
    # >> group_by( *[_[g] for g in groups])

    # Note the use of _[, rather than _[[,
    # and the **{ syntax
    >> mutate( **{new_var: _[var].mean()} )

    # R code ---
    # group_by(across(groups)) %>%
    # mutate( {{new_var}} := mean(!!sym(var)) )
) 
```

Most of what makes the NSE work in siuba is python's [argument unpacking syntax](https://docs.python.org/3/tutorial/controlflow.html#unpacking-argument-lists) with `*` and `**`.

What do you think of this approach using things like `**{`?

**Comment by GitHunter0** [comment]
Hey @machow , thanks for the very helpful feedback, it is really cool to see the NSE capabilities of `siuba`!
Although `**{` deviates from dplyr style, it is effective and not a difficult syntax to remember. Moreover, I appreciate your goal to give `siuba` a fine and robust NSE support. Keep the great work
