### ISSUE TITLE
Add scoped verbs

### ISSUE THREAD

**Issue by essicolo** [machow/siuba#318]
Add scoped verbs `_if`, `_at` and `_all` for `summarize`, `mutate`, `transmute`, `select`, `arrange`, `rename`, `group_by` and `filter` operations, as made available by dplyr and described here https://dplyr.tidyverse.org/reference/scoped.html.

**Comment by GitHunter0** [comment]
The new dplyr 1.0.0 syntax uses across(), scoped verbs (_if, _at, _all) have been superseded

**Comment by machow** [comment]
related to #330, where I jotted out a proposal for `across()`!
