### ISSUE TITLE
filter(): %in% %notin% | & operators and slice() operation

### ISSUE THREAD

**Issue by GitHunter0** [machow/siuba#320]
Hey @machow , I hope you are doing well.

I have some questions and suggestions regarding `filter()` that I would like to discuss here if I may.

(1) Enable logical operators `&`, `|`, or `and`, `or` inside filter(). Right now I could not find a way to use `or` logic, for example: `filter(_.x>2 | ._x==0.5)`

(2) Would you consider implementing `%in%` (and `%notin%`) operators to do something like `filter(_.country %in% ['Australia', 'Ireland'])` ? Currently we have to rely on pandas syntax `filter(_.country.isin(["Australia","Ireland"])` 

(3) Since `siuba` currently does not have `slice()`, is there an easy way to accomplish the same task using `filter()`?

Thank you

**Comment by machow** [comment]
Hey! Thanks for raising. I think for (1), python operator precedence requires parentheses around the lhs and rhs of the & (it's too bad, but part of the language..), and am not sure how we could get (2). We would have to use another operator, since AFAIK python can't create new operators.

3 is definitely something siuba can and should do!

**Comment by GitHunter0** [comment]
Hey, thanks for the feedback!

(2) I don't know too. There is an existing `in` operator that works for lists but unfortunately it does not work inside pandas

(3) Although I'm not sure I have the knowledge required for the task, with your guidelines I definitively can try ;) 

PS: I believe the best workaround for (3) currently is something like this:
```
from siuba.dply.vector import row_number
df >> filter(row_number(_) <= 10)
```

**Comment by davidwales** [comment]
The `in` operator relies on the `__contains__(a, b)` method being defined for the object on the right-hand side. This means that you would need to create a `siuba` aware wrapper class for sequences.

The wrapper would define the `__contains__(a, b)` method.

``` python
class SiubaSequenceWrapper:
    def __init__(self, value):
        self.value = value
    def __contains__(self, other):
        return other.isin(self.value)
```

The final syntax would be:

``` python
filter(_.country in SiubaSequenceWrapper(['Australia', 'Ireland']))
```

I'm sure you can think of a better name for the wrapper...
(This is how you *can* do it. I don't know if you *should* do it!)

**Comment by GitHunter0** [comment]
@davidwales , thanks for insight!
Unfortunately, regardless of the name, having to add a wrapper would kill the purpose of simplifying the syntax in my opinion.
However, this approach may be useful in other contexts.

**Comment by machow** [comment]
@davidwales unfortunately the __contains__ method requires that you return a Boolean :/. AFAIK siuba's symbolic class can't handle __iter__, __contains__, or the keywords `and`, `or` (these keywords throw errors for pandas and bumpy arrays too for the same reason).

**Comment by davidwales** [comment]
@machow, you're right! Unlike the other comparison operators, the result of `__contains__` is unconditionally coerced to a boolean, which means my suggestion above cannot work at all.

**Comment by GitHunter0** [comment]
Hi @machow , this is not directly related to this issue but have you seen this [plydata](https://github.com/has2k1/plydata) package? It is from the same creator of [plotnine](https://github.com/has2k1/plotnine) and has [many verbs already implemented](https://plydata.readthedocs.io/en/stable/api.html#) and I thought it could possibly help you in some way.

**Comment by machow** [comment]
Hey--going back through issues. I've opened up an issue to track adding `slice` :)

https://github.com/machow/siuba/issues/362
