### ISSUE TITLE
Having trouble getting lengths/number of rows within grouped data

### ISSUE THREAD

**Issue by grand-home-projects** [machow/siuba#323]
Hello, I am trying to replicate a task I would commonly use within R dplyr to create a new column based off of running row counts within groups. 

Here is a sample of what the code would usually look like in R:
``new_df <- orig_df  %>%
    select(a, b, c) %>%
    group_by(a, b) %>%
    mutate(running_col = 1:n()) ``

This would result in a df with a new vector, where each group would have its own running "index" from 1 to the total number of rows within that group.

I have tried to implement this in Python+siuba as follows:
``new_df = (orig_df
    >> select(_.a, _.b, _.c)
    >> group_by(_.a, _.b)
    >> mutate(running_col = np.arange(1, len(_) + 1))
    ) ``

I have also tried a few variations on the mutate, using count(), and shape[0] to try to get the total number of rows within each group (as well as by specifying particular columns), but each time an error comes back to tell me that I cannot use them on a "Symbolic" object (I'm assuming that is the "_" that is getting passed as the df placeholder) and it cannot be interpreted properly. 

If that is the case, is there another way to do this kind of mutate for a running count within the groups?

Thanks for any help, and wanted to let you know that I greatly appreciate your awesome library!

**Comment by machow** [comment]
Hey, thanks for checking out siuba! There is a special function that you can import to replicate dplyr's `n`.

```
from siuba.dply.vector import n
from siuba.data import mtcars
From siuba import *

mutate(mtcars, n=n(_))
```

You can also use the pandas method `.size`, but unfortunately it does different things depending on whether you call it on a dataframe or on a series :/. There's also `.shape[0]`.

Here's a list of dplyr vector functions siuba has implemented!:

* https://siuba.readthedocs.io/en/latest/api_extra/vector.html
* also forcats: https://siuba.readthedocs.io/en/latest/api_extra/forcats.html

**Comment by machow** [comment]
Going to close--happy to answer any questions / follow-up!
