### ISSUE TITLE
case_when() - using special symbolic objects like [ `and`,  `&`,  `or`,   `|`  ]

### ISSUE THREAD

**Issue by caspercrause** [machow/siuba#328]
I'm so pleased with this package!

I recently tried classifying blood pressure readings which need to check more than one field to make a diagnosis.

siuba raised an error saying no special symbolic objects are allowed.

This would be such a useful feature to have!

GREAT work on this package so far. I love it!

![image](https://user-images.githubusercontent.com/60570140/121572268-462e3980-ca24-11eb-8446-953af2eaa97d.png)

**Comment by machow** [comment]
Hey, glad you're enjoying the package! AFAICT this is actually a haunting detail of Python's & and | operators. The tldr is using parentheses on both sides like `(_.SYS < 60) & (_.OTHER < 90)` should fix.

Statements like ..

```
1 > 2 & True
```

Are equivalent to

```
1 > (2 & True)
```

https://docs.python.org/3/reference/expressions.html#operator-precedence

**Comment by caspercrause** [comment]
Thanks! This worked. We can close this issue. @machow
