### ISSUE TITLE
Using plotly with siuba

### ISSUE THREAD

**Issue by omrihar** [machow/siuba#329]
Hello,

In the recent months I've grown to rely on siuba for all of my data wrangling needs, and was using plotnine to plot the outcomes. However, I would like to use more interactive plotting engines, such as plotly, and would love to be able to combine this with the pipe symbol. 
Is there a nice way to pipe the results into a plotly (or any other) unaware plotting function? I've tried something along the lines of 
```
(
    df
    >> some_operations()...
    >> px.bar(_, x='...', y='...')
)
```
but this raises a `ValueError: DataFrame constructor not properly called!` error. I tried digging a bit into the code of both `siuba` and `plotnine` but I couldn't really figure this out.

Any help would appreciated!
Cheers,
Omri

**Comment by essicolo** [comment]
Hi,

It works with a `lambda` function inside `pipe`.

```
import plotly.express as px
from siuba import *
from siuba.data import mtcars

(mtcars
    >> filter(_.cyl >= 6)
    >> pipe(lambda d: px.scatter(
        data_frame = d,
        x = 'wt',
        y = 'mpg',
        facet_col = 'gear'
    ))
)
```

I think that plotnine.ggplot with siuba works without the pipe function since it takes `data` as its first argument, while px.scatter uses `data_frame`.

**Comment by omrihar** [comment]
Oh that's interesting! 
Thank you @essicolo :) I didn't know about the `pipe` verb - I'll definitely try to use it more often :)

**Comment by essicolo** [comment]
`pipe` is indeed very flexible. It would be convenient though to parse plotly functions (or seaborn, altair, etc.) as done with plotnine or as @omrihar wrote in the issue description. @machow, what do you think?
