### ISSUE TITLE
Convert lazy object into local dataframe

### ISSUE THREAD

**Issue by loeuf-quatre** [machow/siuba#335]
Native R guy here embedded in a Python-heavy team. I can't let go of the pipes so I have high hopes for this!

I managed to link up to a Trino database but can't figure out how to bring my lazy query results into my local environment as a Pandas df akin to just calling `data.frame()` in R. My attempts at calling `pd.DataFrame()` return `TypeError: unsupported operand type(s) for >>: 'LazyTbl' and 'DataFrame'`. Quite likely I'm missing something but I've spent an hour poking around the documentation to no avail.

**Comment by machow** [comment]
Hey--does using `collect()` work, similar to dbplyr?

```python
from siuba import collect
from siuba.sql import LazyTbl

tbl = LazyTbl(...)
tbl >> collect()
```

I'd be curious to hear how you got everything set up for Trino. Are you using the postgresql dialect? I've implemented bigquery into siuba for work, so am keen on knocking down more SQL backends :)

**Comment by machow** [comment]
Hey, going to close--but let me know if `collect()` doesn't work for you
