### ISSUE TITLE
if else statement in mutate function 

### ISSUE THREAD

**Issue by TonyFly3000** [machow/siuba#342]
Hi Michael,

Could we use if else statement in mutate function? I found this part is empty in the document.

https://siuba.readthedocs.io/en/latest/api_table_core/05_mutate.html#With-if_else-and-case_when

Thanks

**Comment by essicolo** [comment]
You can!

```
from siuba import *
from siuba.data import mtcars

(
    mtcars
    >> mutate(hp_category = if_else(_.hp >= 150, "high hp", "low hp"))
)
```

**Comment by machow** [comment]
I've added a page in the siuba guide showing if_else used outside and inside of verbs :)

https://siuba.org/guide/ops-case-when.html
