### ISSUE TITLE
fct_reorder

### ISSUE THREAD

**Issue by willros** [machow/siuba#343]
Hi,

When i use fct_reorder on data that should work, I get this error message: 
codes need to be array-like integers

Do you know what is going wrong?
Thanks for a great package!

**Comment by pwwang** [comment]
It should be a pandas bug. See:

https://github.com/pandas-dev/pandas/issues/42433
and
https://github.com/pandas-dev/pandas/issues/42431

A possible fix would be changing:

https://github.com/machow/siuba/blob/5cb367f1bf4e1552e90ffaeba286ba54f643d7b9/siuba/dply/forcats.py#L40

to:

```python
 codes = ordered[list(s.index.values)] 
```

**Comment by machow** [comment]
Should be resolved by #366, thanks for taking a look!
