### ISSUE TITLE
Aggregating functions on Symbolic objects in Lazy tables

### ISSUE THREAD

**Issue by ivdim1999** [machow/siuba#345]
When testing out siuba in the last few days I've come to a struggle when trying to use aggregating functions on `Symbolic` objects.

I am using a `LazyTbl` with the idea that sometimes there's going to be a lot of data in the database and having the ability
to generate siuba/SQL expressions lazily will help out. 

An issue I have encountered (and haven't found a fix for in the [documentation](https://siuba.readthedocs.io/_/downloads/en/latest/pdf/) is how to handle aggregating functions on `Symbolic` objects. The specific case I have is:

```
from siuba import _ as t

@singledispatch2((Table, siuba.sql.LazyTbl, pandas.DataFrame))
def specific_mutate_logical_expr(__data, group_cols, coalesced_col, compared_col, some_col):
    __data = (__data >> group_by(*group_cols)) >> mutate(
        **{some_col + str(i): any(getattr(t, some_col) & ((getattr(t, compared_col) == str(i)) |
                                                       coalesce(getattr(t, coalesced_col) == str(i), False)))
           for i in range(6)})
    return __data

```

Here I try to define a mutate that does some complicated sequence of logical expressions on some columns (context isn't important). The important part is the `any(long symbolic expression)` statement that in SQL should read `BOOL_OR(expression, containing several columns)`. However `any()` doesn't seem to be translatable in siuba and gives the error:

```
TypeError: 'Symbolic' object is not iterable.
```

A similar issue has been brought up in issue [334](https://github.com/machow/siuba/issues/334), however the difference is that in this case a `pandas.DataFrame` is used for which a workaround using `transform` could potentially be possible.

However such a workaround for `Symbolic` doesn't seem to be available at least at first glance.

**Comment by machow** [comment]
What SQL dialect are you using? Can you show how you connect with siuba?

It looks like I need to add this to the docs, but for singledispatch to work with siuba right now, it needs to report the type it is outputting (or use the Any type)

Here is an example of how I registered the SQL for a between() function

https://github.com/machow/siuba/blob/master/siuba/sql/dply/vector.py#L111

**Comment by ivdim1999** [comment]
Ok, it was a problem on my part - I loaded up an in memory sqlite database and for some reason thought I was using Postgres. So thanks for pointing that out. On Postgres, the `pandas` methods get translated (`.any()` turns into `bool_or()`), however pythonic `any()` doesn't. I guess it's because of the fact that it's hardcoded in python itself to only recognize iterables. Idk if it would make any sense to try to adapt any of the pythonic functions as they have `pandas` equivalents.

Once again, thanks.
