### ISSUE TITLE
summarize() can't use np.sqrt 

### ISSUE THREAD

**Issue by HuangHam** [machow/siuba#399]
Hi! So glad to find a tidyverse equivalent in python. I encountered the following issue:

data = pd.concat([df_human, df_sim]) >> \
       group_by(_.subj, _.trial, _.split, _.agent,_.inequality) >> \
       summarize(reward = np.sqrt(np.mean(_.reward)))

Note I wanted the square root of the mean of the variable named reward. but this gives me an error: invalid __array_struct__ . This error doesn't show up for other np functions such as np.size, np.mean, np.std. So I'm really confused...

**Comment by machow** [comment]
Fixed in version `0.2.3`!

```python
from siuba.data import mtcars
from siuba import _, mutate, group_by
import numpy as np

mtcars >> group_by(_.cyl) >> mutate(res = np.sqrt(np.mean(_.hp)))
```
