### ISSUE TITLE
Better support for plotting libraries

### ISSUE THREAD

**Issue by essicolo** [machow/siuba#408]
Siuba works with plotnine directly after `>>`, as

```{python}
from siuba import _, mutate
from siuba.data import mtcars
import plotnine as p9

(mtcars
    >> mutate(hp_per_cyl = _.hp / _.cyl)
    >> p9.ggplot(p9.aes(x='cyl', y='hp_per_cyl')) + p9.geom_point()
)
```

... but needs a `pipe` to work with other plotting libraries like seaborn, altair, lets-plot, plotly, etc., as

```{python}
from siuba import pipe
import plotly.express as px

(mtcars
    >> mutate(hp_per_cyl = _.hp / _.cyl)
    >> pipe(lambda d: px.scatter(data_frame=d, x='cyl', y='hp_per_cyl'))
)
```

Could other plotting libraries be supported directly after the `>>`?

**Comment by machow** [comment]
@essicolo exploring this now--what do you think of #413 ?

It should allow this:

```python
from siuba import _, mutate, pipe as P
from siuba.data import mtcars

import plotly.express as px

(mtcars
    >> mutate(hp_per_cyl = _.hp / _.cyl)
    >> P(px.scatter, _, x='cyl', y='hp_per_cyl')
    # equiv to px.scatter(some_data, x='cyl', y='hp_per_cyl')
)
```

Note that you can also do anything to `_`, so could do things like

```python
# arbitrary siu expressions allowed
... >> P(px.scatter, _[["mpg", "hp"]], ...)
```

or pass the data as a different argument

```python
"\n\n" >> P(print, "a", "b", sep = _)
# a
# 
# b
```

**Comment by essicolo** [comment]
Hi @machow, It looks awesome! I suggest using `pipe` instead of `P` in the documentation, though.

**Comment by machow** [comment]
Ah, okay--thanks for the feedback! I'll add some docs on it, but then should be pretty straightforward to release!

**Comment by machow** [comment]
Oh interesting--how about `>>` being the "pipe operator" and `pipe` the "pipe function", where `pipe` makes sure that the operator always works?

**Comment by essicolo** [comment]
Agreed. Or is naming `pipe` otherwise an option? Is there a grammar for a similar function in dplyr?

**Comment by machow** [comment]
I think R can side-steps the need for a `pipe` function by using non-standard evaluation 😬
