### ISSUE TITLE
default output for LazyTbl

### ISSUE THREAD

**Issue by adrian-soto** [machow/siuba#6]
It would be useful if every time a `LazyTbl` object is invoked, the first few rows of the table were displayed (similar to `dbplyr`). This could be done by adding a `__repr__()` method (and a `_repr_html_()` for jupyter notebooks) or by adding a `__call__()` method in the `LazyTbl` class.

cc: @machow @adrian-datacamp

**Comment by machow** [comment]
Done! https://github.com/machow/siuba/pull/9

![image](https://user-images.githubusercontent.com/2574498/56935718-efbe4500-6ac0-11e9-8007-dbaaa9503856.png)

**Comment by adrian-soto** [comment]
🎉
